Restrict reference by ID to numeric values on integer fields
#241 introduced regression when using entity labels with a postgres database

SQLSTATE[22P02]: Invalid text representation: 7
 ERROR: invalid input syntax for type bigint